// types.h
#ifndef TYPES_H
#define TYPES_H

enum screen_t {
    SCREEN_HOME,
    SCREEN_NOA,
    SCREEN_MAIA,
    SCREEN_BOOKCASE,
    SCREEN_STAIRS
};

screen_t screensArray[] = {
    SCREEN_HOME,
    SCREEN_NOA,
    SCREEN_MAIA,
    SCREEN_BOOKCASE,
    SCREEN_STAIRS
};

enum voice_command_t {
    Silence = 0x00,
    WakeUpWordsForLearning = 0x01,
    HelloRobot = 0x02,
    CustomCommand1 = 0x05,
    CustomCommand2 = 0x06,
    CustomCommand3 = 0x07,
    CustomCommand4 = 0x08,
    CustomCommand5 = 0x09,
    CustomCommand6 = 0x0A,
    CustomCommand7 = 0x0B,
    CustomCommand8 = 0x0C,
    CustomCommand9 = 0x0D,
    CustomCommand10 = 0x0E,
    CustomCommand11 = 0x0F,
    CustomCommand12 = 0x10,
    CustomCommand13 = 0x11,
    CustomCommand14 = 0x12,
    CustomCommand15 = 0x13,
    CustomCommand16 = 0x14,
    CustomCommand17 = 0x15,
    GoForward = 0x16,
    Retreat = 0x17,
    ParkACar = 0x18,
    TurnLeftNinetyDegrees = 0x19,
    TurnLeftFortyFiveDegrees = 0x1A,
    TurnLeftThirtyDegrees = 0x1B,
    TurnRightFortyFiveDegrees = 0x1D,
    TurnRightThirtyDegrees = 0x1E,
    ShiftDownAGear = 0x1F,
    LineTrackingMode = 0x20,
    LightTrackingMode = 0x21,
    BluetoothMode = 0x22,
    ObstacleAvoidanceMode = 0x23,
    FaceRecognition = 0x24,
    ObjectTracking = 0x25,
    ObjectRecognition = 0x26,
    LineTracking = 0x27,
    ColorRecognition = 0x28,
    TagRecognition = 0x29,
    ObjectSorting = 0x2A,
    QrCodeRecognition = 0x2B,
    GeneralSettings = 0x2C,
    ClearScreen = 0x2D,
    LearnOnce = 0x2E,
    Forget = 0x2F,
    LoadModel = 0x30,
    SaveModel = 0x31,
    TakePhotosAndSaveThem = 0x32,
    SaveAndReturn = 0x33,
    DisplayNumberZero = 0x34,
    DisplayNumberOne = 0x35,
    DisplayNumberTwo = 0x36,
    DisplayNumberThree = 0x37,
    DisplayNumberFour = 0x38,
    DisplayNumberFive = 0x39,
    DisplayNumberSix = 0x3A,
    DisplayNumberSeven = 0x3B,
    DisplayNumberEight = 0x3C,
    DisplayNumberNine = 0x3D,
    DisplaySmileyFace = 0x3E,
    DisplayCryingFace = 0x3F,
    DisplayHeart = 0x40,
    TurnOffDotMatrix = 0x41,
    ReadCurrentPosture = 0x42,
    ReadAmbientLight = 0x43,
    ReadCompass = 0x44,
    ReadTemperature = 0x45,
    ReadAcceleration = 0x46,
    ReadingSoundIntensity = 0x47,
    CalibrateElectronicGyroscope = 0x48,
    TurnOnTheCamera = 0x49,
    TurnOffTheCamera = 0x4A,
    TurnOnTheFan = 0x4B,
    TurnOffTheFan = 0x4C,
    TurnFanSpeedToGearOne = 0x4D,
    TurnFanSpeedToGearTwo = 0x4E,
    TurnFanSpeedToGearThree = 0x4F,
    StartOscillating = 0x50,
    StopOscillating = 0x51,
    Reset = 0x52,
    SetServoToTenDegrees = 0x53,
    SetServoToThirtyDegrees = 0x54,
    SetServoToFortyFiveDegrees = 0x55,
    SetServoToSixtyDegrees = 0x56,
    SetServoToNinetyDegrees = 0x57,
    TurnOnTheBuzzer = 0x58,
    TurnOffTheBuzzer = 0x59,
    TurnOnTheSpeaker = 0x5A,
    TurnOffTheSpeaker = 0x5B,
    PlayMusic = 0x5C,
    StopPlaying = 0x5D,
    TheLastTrack = 0x5E,
    TheNextTrack = 0x5F,
    RepeatThisTrack = 0x60,
    VolumeUp = 0x61,
    VolumeDown = 0x62,
    ChangeVolumeToMaximum = 0x63,
    ChangeVolumeToMinimum = 0x64,
    ChangeVolumeToMedium = 0x65,
    PlayPoem = 0x66,
    TurnOnTheLight = 0x67,
    TurnOffTheLight = 0x68,
    BrightenTheLight = 0x69,
    DimTheLight = 0x6A,
    AdjustBrightnessToMaximum = 0x6B,
    AdjustBrightnessToMinimum = 0x6C,
    IncreaseColorTemperature = 0x6D,
    DecreaseColorTemperature = 0x6E,
    AdjustColorTemperatureToMaximum = 0x6F,
    AdjustColorTemperatureToMinimum = 0x70,
    DaylightMode = 0x71,
    MoonlightMode = 0x72,
    ColorMode = 0x73,
    SetToRed = 0x74,
    SetToOrange = 0x75,
    SetToYellow = 0x76,
    SetToGreen = 0x77,
    SetToCyan = 0x78,
    SetToBlue = 0x79,
    SetToPurple = 0x7A,
    SetToWhite = 0x7B,
    TurnOnAc = 0x7C,
    TurnOffAc = 0x7D,
    IncreaseTemperature = 0x7E,
    DecreaseTemperature = 0x7F,
    CoolMode = 0x80,
    HeatMode = 0x81,
    AutoMode = 0x82,
    DryMode = 0x83,
    FanMode = 0x84,
    EnableBlowingUpDown = 0x85,
    DisableBlowingUpDown = 0x86,
    EnableBlowingRightLeft = 0x87,
    DisableBlowingRightLeft = 0x88,
    OpenTheWindow = 0x89,
    CloseTheWindow = 0x8A,
    OpenCurtain = 0x8B,
    CloseCurtain = 0x8C,
    OpenTheDoor = 0x8D,
    CloseTheDoor = 0x8E,
    LearningWakeWord = 0xC8,
    LearningCommandWord = 0xC9,
    ReLearn = 0xCA,
    ExitLearning = 0xCB,
    IWantToDelete = 0xCC,
    DeleteWakeWord = 0xCD,
    DeleteCommandWord = 0xCE,
    ExitDeleting = 0xCF,
    DeleteAll = 0xD0,
};

#endif
